# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build next-bot`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t next-bot`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system next-bot && \
          adduser --system -G next-bot next-bot

COPY dist/next-bot next-bot
RUN chown -R next-bot:next-bot .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix next-bot --omit=dev -f install

CMD [ "node", "next-bot" ]
