name: "NeXTLinux SBOM Action / Download Gosbom"
description: "Downloads Gosbom to the Action tool cache and provides a reference"
author: "NeXTLinux"

inputs:
  gosbom-version:
    required: false
    description: "The version of Gosbom to download"

outputs:
  cmd:
    description: "A reference to the Gosbom command"

runs:
  using: "node16"
  main: "../dist/downloadGosbom/index.js"
